# Generated by Django 3.2.10 on 2022-08-11 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
