# Generated by Django 3.2.10 on 2022-08-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_service', '0003_auto_20220811_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
