# Generated by Django 3.2.10 on 2022-08-13 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_service', '0004_auto_20220812_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTokenPushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           related_name='device_token_push_notification_user',
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_token_push_notification',
            },
        ),
    ]
