# Generated by Django 3.2.10 on 2022-08-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_service', '0005_devicetokenpushnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetokenpushnotification',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
