# Generated by Django 3.2.10 on 2022-08-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_service', '0006_devicetokenpushnotification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetokenpushnotification',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
