# Generated by Django 3.2.10 on 2022-10-17 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_service', '0007_devicetokenpushnotification_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisionclass',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_class_subject', to='custom_service.subject'),
        ),
    ]
